/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ShareRouteImport } from './routes/_share'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DriverIndexRouteImport } from './routes/driver/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DriverWalletRouteImport } from './routes/driver/wallet'
import { Route as DriverVehiclesRouteImport } from './routes/driver/vehicles'
import { Route as DriverTransactionsRouteImport } from './routes/driver/transactions'
import { Route as DriverProfileRouteImport } from './routes/driver/profile'
import { Route as DriverOnboardingRouteImport } from './routes/driver/onboarding'
import { Route as AppTransactionsRouteImport } from './routes/app/transactions'
import { Route as AppSearchRouteImport } from './routes/app/search'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTripsRouteImport } from './routes/admin/trips'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminDriversRouteImport } from './routes/admin/drivers'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as PublicTripsRouteImport } from './routes/_public/trips'
import { Route as PublicSafetyRouteImport } from './routes/_public/safety'
import { Route as PublicDriversInfoRouteImport } from './routes/_public/drivers-info'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as DriverTripsIndexRouteImport } from './routes/driver/trips/index'
import { Route as AppBookingsIndexRouteImport } from './routes/app/bookings/index'
import { Route as TripsIdLocationRouteImport } from './routes/trips.$id.location'
import { Route as DriverTripsNewRouteImport } from './routes/driver/trips/new'
import { Route as DriverTripsIdRouteImport } from './routes/driver/trips/$id'
import { Route as DriverTransactionsIdRouteImport } from './routes/driver/transactions.$id'
import { Route as AppTripsIdRouteImport } from './routes/app/trips/$id'
import { Route as AppTransactionsIdRouteImport } from './routes/app/transactions.$id'
import { Route as AppPaymentsCallbackRouteImport } from './routes/app/payments.callback'
import { Route as AppBookingsIdRouteImport } from './routes/app/bookings/$id'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users.$id'
import { Route as AdminPaymentsIdRouteImport } from './routes/admin/payments.$id'
import { Route as ShareTTripIdRouteImport } from './routes/_share/t.$tripId'
import { Route as ShareDDriverIdRouteImport } from './routes/_share/d.$driverId'
import { Route as DriverTripsIdEditRouteImport } from './routes/driver/trips/$id/edit'

const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/_share',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const DriverWalletRoute = DriverWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DriverRoute,
} as any)
const DriverVehiclesRoute = DriverVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => DriverRoute,
} as any)
const DriverTransactionsRoute = DriverTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DriverRoute,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverRoute,
} as any)
const DriverOnboardingRoute = DriverOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DriverRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const PublicTripsRoute = PublicTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSafetyRoute = PublicSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDriversInfoRoute = PublicDriversInfoRouteImport.update({
  id: '/drivers-info',
  path: '/drivers-info',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const DriverTripsIndexRoute = DriverTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => DriverRoute,
} as any)
const AppBookingsIndexRoute = AppBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AppRoute,
} as any)
const TripsIdLocationRoute = TripsIdLocationRouteImport.update({
  id: '/trips/$id/location',
  path: '/trips/$id/location',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTripsNewRoute = DriverTripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => DriverRoute,
} as any)
const DriverTripsIdRoute = DriverTripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => DriverRoute,
} as any)
const DriverTransactionsIdRoute = DriverTransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DriverTransactionsRoute,
} as any)
const AppTripsIdRoute = AppTripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsIdRoute = AppTransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTransactionsRoute,
} as any)
const AppPaymentsCallbackRoute = AppPaymentsCallbackRouteImport.update({
  id: '/payments/callback',
  path: '/payments/callback',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsIdRoute = AppBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminPaymentsIdRoute = AdminPaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPaymentsRoute,
} as any)
const ShareTTripIdRoute = ShareTTripIdRouteImport.update({
  id: '/t/$tripId',
  path: '/t/$tripId',
  getParentRoute: () => ShareRoute,
} as any)
const ShareDDriverIdRoute = ShareDDriverIdRouteImport.update({
  id: '/d/$driverId',
  path: '/d/$driverId',
  getParentRoute: () => ShareRoute,
} as any)
const DriverTripsIdEditRoute = DriverTripsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DriverTripsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/drivers-info': typeof PublicDriversInfoRoute
  '/safety': typeof PublicSafetyRoute
  '/trips': typeof PublicTripsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/payments': typeof AdminPaymentsRouteWithChildren
  '/admin/trips': typeof AdminTripsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/transactions': typeof AppTransactionsRouteWithChildren
  '/driver/onboarding': typeof DriverOnboardingRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/transactions': typeof DriverTransactionsRouteWithChildren
  '/driver/vehicles': typeof DriverVehiclesRoute
  '/driver/wallet': typeof DriverWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/d/$driverId': typeof ShareDDriverIdRoute
  '/t/$tripId': typeof ShareTTripIdRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/app/bookings/$id': typeof AppBookingsIdRoute
  '/app/payments/callback': typeof AppPaymentsCallbackRoute
  '/app/transactions/$id': typeof AppTransactionsIdRoute
  '/app/trips/$id': typeof AppTripsIdRoute
  '/driver/transactions/$id': typeof DriverTransactionsIdRoute
  '/driver/trips/$id': typeof DriverTripsIdRouteWithChildren
  '/driver/trips/new': typeof DriverTripsNewRoute
  '/trips/$id/location': typeof TripsIdLocationRoute
  '/app/bookings/': typeof AppBookingsIndexRoute
  '/driver/trips/': typeof DriverTripsIndexRoute
  '/driver/trips/$id/edit': typeof DriverTripsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/drivers-info': typeof PublicDriversInfoRoute
  '/safety': typeof PublicSafetyRoute
  '/trips': typeof PublicTripsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/payments': typeof AdminPaymentsRouteWithChildren
  '/admin/trips': typeof AdminTripsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/transactions': typeof AppTransactionsRouteWithChildren
  '/driver/onboarding': typeof DriverOnboardingRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/transactions': typeof DriverTransactionsRouteWithChildren
  '/driver/vehicles': typeof DriverVehiclesRoute
  '/driver/wallet': typeof DriverWalletRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/driver': typeof DriverIndexRoute
  '/d/$driverId': typeof ShareDDriverIdRoute
  '/t/$tripId': typeof ShareTTripIdRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/app/bookings/$id': typeof AppBookingsIdRoute
  '/app/payments/callback': typeof AppPaymentsCallbackRoute
  '/app/transactions/$id': typeof AppTransactionsIdRoute
  '/app/trips/$id': typeof AppTripsIdRoute
  '/driver/transactions/$id': typeof DriverTransactionsIdRoute
  '/driver/trips/$id': typeof DriverTripsIdRouteWithChildren
  '/driver/trips/new': typeof DriverTripsNewRoute
  '/trips/$id/location': typeof TripsIdLocationRoute
  '/app/bookings': typeof AppBookingsIndexRoute
  '/driver/trips': typeof DriverTripsIndexRoute
  '/driver/trips/$id/edit': typeof DriverTripsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_share': typeof ShareRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/drivers-info': typeof PublicDriversInfoRoute
  '/_public/safety': typeof PublicSafetyRoute
  '/_public/trips': typeof PublicTripsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/payments': typeof AdminPaymentsRouteWithChildren
  '/admin/trips': typeof AdminTripsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/transactions': typeof AppTransactionsRouteWithChildren
  '/driver/onboarding': typeof DriverOnboardingRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/transactions': typeof DriverTransactionsRouteWithChildren
  '/driver/vehicles': typeof DriverVehiclesRoute
  '/driver/wallet': typeof DriverWalletRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/_share/d/$driverId': typeof ShareDDriverIdRoute
  '/_share/t/$tripId': typeof ShareTTripIdRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/app/bookings/$id': typeof AppBookingsIdRoute
  '/app/payments/callback': typeof AppPaymentsCallbackRoute
  '/app/transactions/$id': typeof AppTransactionsIdRoute
  '/app/trips/$id': typeof AppTripsIdRoute
  '/driver/transactions/$id': typeof DriverTransactionsIdRoute
  '/driver/trips/$id': typeof DriverTripsIdRouteWithChildren
  '/driver/trips/new': typeof DriverTripsNewRoute
  '/trips/$id/location': typeof TripsIdLocationRoute
  '/app/bookings/': typeof AppBookingsIndexRoute
  '/driver/trips/': typeof DriverTripsIndexRoute
  '/driver/trips/$id/edit': typeof DriverTripsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/driver'
    | '/about'
    | '/contact'
    | '/drivers-info'
    | '/safety'
    | '/trips'
    | '/admin/bookings'
    | '/admin/drivers'
    | '/admin/payments'
    | '/admin/trips'
    | '/admin/users'
    | '/app/profile'
    | '/app/search'
    | '/app/transactions'
    | '/driver/onboarding'
    | '/driver/profile'
    | '/driver/transactions'
    | '/driver/vehicles'
    | '/driver/wallet'
    | '/admin/'
    | '/app/'
    | '/driver/'
    | '/d/$driverId'
    | '/t/$tripId'
    | '/admin/payments/$id'
    | '/admin/users/$id'
    | '/app/bookings/$id'
    | '/app/payments/callback'
    | '/app/transactions/$id'
    | '/app/trips/$id'
    | '/driver/transactions/$id'
    | '/driver/trips/$id'
    | '/driver/trips/new'
    | '/trips/$id/location'
    | '/app/bookings/'
    | '/driver/trips/'
    | '/driver/trips/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/drivers-info'
    | '/safety'
    | '/trips'
    | '/admin/bookings'
    | '/admin/drivers'
    | '/admin/payments'
    | '/admin/trips'
    | '/admin/users'
    | '/app/profile'
    | '/app/search'
    | '/app/transactions'
    | '/driver/onboarding'
    | '/driver/profile'
    | '/driver/transactions'
    | '/driver/vehicles'
    | '/driver/wallet'
    | '/admin'
    | '/app'
    | '/driver'
    | '/d/$driverId'
    | '/t/$tripId'
    | '/admin/payments/$id'
    | '/admin/users/$id'
    | '/app/bookings/$id'
    | '/app/payments/callback'
    | '/app/transactions/$id'
    | '/app/trips/$id'
    | '/driver/transactions/$id'
    | '/driver/trips/$id'
    | '/driver/trips/new'
    | '/trips/$id/location'
    | '/app/bookings'
    | '/driver/trips'
    | '/driver/trips/$id/edit'
  id:
    | '__root__'
    | '/_public'
    | '/_share'
    | '/admin'
    | '/app'
    | '/driver'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/drivers-info'
    | '/_public/safety'
    | '/_public/trips'
    | '/admin/bookings'
    | '/admin/drivers'
    | '/admin/payments'
    | '/admin/trips'
    | '/admin/users'
    | '/app/profile'
    | '/app/search'
    | '/app/transactions'
    | '/driver/onboarding'
    | '/driver/profile'
    | '/driver/transactions'
    | '/driver/vehicles'
    | '/driver/wallet'
    | '/_public/'
    | '/admin/'
    | '/app/'
    | '/driver/'
    | '/_share/d/$driverId'
    | '/_share/t/$tripId'
    | '/admin/payments/$id'
    | '/admin/users/$id'
    | '/app/bookings/$id'
    | '/app/payments/callback'
    | '/app/transactions/$id'
    | '/app/trips/$id'
    | '/driver/transactions/$id'
    | '/driver/trips/$id'
    | '/driver/trips/new'
    | '/trips/$id/location'
    | '/app/bookings/'
    | '/driver/trips/'
    | '/driver/trips/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  ShareRoute: typeof ShareRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  DriverRoute: typeof DriverRouteWithChildren
  TripsIdLocationRoute: typeof TripsIdLocationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_share': {
      id: '/_share'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/driver/wallet': {
      id: '/driver/wallet'
      path: '/wallet'
      fullPath: '/driver/wallet'
      preLoaderRoute: typeof DriverWalletRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/vehicles': {
      id: '/driver/vehicles'
      path: '/vehicles'
      fullPath: '/driver/vehicles'
      preLoaderRoute: typeof DriverVehiclesRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/transactions': {
      id: '/driver/transactions'
      path: '/transactions'
      fullPath: '/driver/transactions'
      preLoaderRoute: typeof DriverTransactionsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/onboarding': {
      id: '/driver/onboarding'
      path: '/onboarding'
      fullPath: '/driver/onboarding'
      preLoaderRoute: typeof DriverOnboardingRouteImport
      parentRoute: typeof DriverRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/trips': {
      id: '/_public/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof PublicTripsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/safety': {
      id: '/_public/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof PublicSafetyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/drivers-info': {
      id: '/_public/drivers-info'
      path: '/drivers-info'
      fullPath: '/drivers-info'
      preLoaderRoute: typeof PublicDriversInfoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/driver/trips/': {
      id: '/driver/trips/'
      path: '/trips'
      fullPath: '/driver/trips/'
      preLoaderRoute: typeof DriverTripsIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/app/bookings/': {
      id: '/app/bookings/'
      path: '/bookings'
      fullPath: '/app/bookings/'
      preLoaderRoute: typeof AppBookingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/trips/$id/location': {
      id: '/trips/$id/location'
      path: '/trips/$id/location'
      fullPath: '/trips/$id/location'
      preLoaderRoute: typeof TripsIdLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/trips/new': {
      id: '/driver/trips/new'
      path: '/trips/new'
      fullPath: '/driver/trips/new'
      preLoaderRoute: typeof DriverTripsNewRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/trips/$id': {
      id: '/driver/trips/$id'
      path: '/trips/$id'
      fullPath: '/driver/trips/$id'
      preLoaderRoute: typeof DriverTripsIdRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/transactions/$id': {
      id: '/driver/transactions/$id'
      path: '/$id'
      fullPath: '/driver/transactions/$id'
      preLoaderRoute: typeof DriverTransactionsIdRouteImport
      parentRoute: typeof DriverTransactionsRoute
    }
    '/app/trips/$id': {
      id: '/app/trips/$id'
      path: '/trips/$id'
      fullPath: '/app/trips/$id'
      preLoaderRoute: typeof AppTripsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions/$id': {
      id: '/app/transactions/$id'
      path: '/$id'
      fullPath: '/app/transactions/$id'
      preLoaderRoute: typeof AppTransactionsIdRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
    '/app/payments/callback': {
      id: '/app/payments/callback'
      path: '/payments/callback'
      fullPath: '/app/payments/callback'
      preLoaderRoute: typeof AppPaymentsCallbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings/$id': {
      id: '/app/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/app/bookings/$id'
      preLoaderRoute: typeof AppBookingsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/payments/$id': {
      id: '/admin/payments/$id'
      path: '/$id'
      fullPath: '/admin/payments/$id'
      preLoaderRoute: typeof AdminPaymentsIdRouteImport
      parentRoute: typeof AdminPaymentsRoute
    }
    '/_share/t/$tripId': {
      id: '/_share/t/$tripId'
      path: '/t/$tripId'
      fullPath: '/t/$tripId'
      preLoaderRoute: typeof ShareTTripIdRouteImport
      parentRoute: typeof ShareRoute
    }
    '/_share/d/$driverId': {
      id: '/_share/d/$driverId'
      path: '/d/$driverId'
      fullPath: '/d/$driverId'
      preLoaderRoute: typeof ShareDDriverIdRouteImport
      parentRoute: typeof ShareRoute
    }
    '/driver/trips/$id/edit': {
      id: '/driver/trips/$id/edit'
      path: '/edit'
      fullPath: '/driver/trips/$id/edit'
      preLoaderRoute: typeof DriverTripsIdEditRouteImport
      parentRoute: typeof DriverTripsIdRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicDriversInfoRoute: typeof PublicDriversInfoRoute
  PublicSafetyRoute: typeof PublicSafetyRoute
  PublicTripsRoute: typeof PublicTripsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicDriversInfoRoute: PublicDriversInfoRoute,
  PublicSafetyRoute: PublicSafetyRoute,
  PublicTripsRoute: PublicTripsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface ShareRouteChildren {
  ShareDDriverIdRoute: typeof ShareDDriverIdRoute
  ShareTTripIdRoute: typeof ShareTTripIdRoute
}

const ShareRouteChildren: ShareRouteChildren = {
  ShareDDriverIdRoute: ShareDDriverIdRoute,
  ShareTTripIdRoute: ShareTTripIdRoute,
}

const ShareRouteWithChildren = ShareRoute._addFileChildren(ShareRouteChildren)

interface AdminPaymentsRouteChildren {
  AdminPaymentsIdRoute: typeof AdminPaymentsIdRoute
}

const AdminPaymentsRouteChildren: AdminPaymentsRouteChildren = {
  AdminPaymentsIdRoute: AdminPaymentsIdRoute,
}

const AdminPaymentsRouteWithChildren = AdminPaymentsRoute._addFileChildren(
  AdminPaymentsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminPaymentsRoute: typeof AdminPaymentsRouteWithChildren
  AdminTripsRoute: typeof AdminTripsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminPaymentsRoute: AdminPaymentsRouteWithChildren,
  AdminTripsRoute: AdminTripsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppTransactionsRouteChildren {
  AppTransactionsIdRoute: typeof AppTransactionsIdRoute
}

const AppTransactionsRouteChildren: AppTransactionsRouteChildren = {
  AppTransactionsIdRoute: AppTransactionsIdRoute,
}

const AppTransactionsRouteWithChildren = AppTransactionsRoute._addFileChildren(
  AppTransactionsRouteChildren,
)

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppTransactionsRoute: typeof AppTransactionsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppBookingsIdRoute: typeof AppBookingsIdRoute
  AppPaymentsCallbackRoute: typeof AppPaymentsCallbackRoute
  AppTripsIdRoute: typeof AppTripsIdRoute
  AppBookingsIndexRoute: typeof AppBookingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppTransactionsRoute: AppTransactionsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppBookingsIdRoute: AppBookingsIdRoute,
  AppPaymentsCallbackRoute: AppPaymentsCallbackRoute,
  AppTripsIdRoute: AppTripsIdRoute,
  AppBookingsIndexRoute: AppBookingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DriverTransactionsRouteChildren {
  DriverTransactionsIdRoute: typeof DriverTransactionsIdRoute
}

const DriverTransactionsRouteChildren: DriverTransactionsRouteChildren = {
  DriverTransactionsIdRoute: DriverTransactionsIdRoute,
}

const DriverTransactionsRouteWithChildren =
  DriverTransactionsRoute._addFileChildren(DriverTransactionsRouteChildren)

interface DriverTripsIdRouteChildren {
  DriverTripsIdEditRoute: typeof DriverTripsIdEditRoute
}

const DriverTripsIdRouteChildren: DriverTripsIdRouteChildren = {
  DriverTripsIdEditRoute: DriverTripsIdEditRoute,
}

const DriverTripsIdRouteWithChildren = DriverTripsIdRoute._addFileChildren(
  DriverTripsIdRouteChildren,
)

interface DriverRouteChildren {
  DriverOnboardingRoute: typeof DriverOnboardingRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverTransactionsRoute: typeof DriverTransactionsRouteWithChildren
  DriverVehiclesRoute: typeof DriverVehiclesRoute
  DriverWalletRoute: typeof DriverWalletRoute
  DriverIndexRoute: typeof DriverIndexRoute
  DriverTripsIdRoute: typeof DriverTripsIdRouteWithChildren
  DriverTripsNewRoute: typeof DriverTripsNewRoute
  DriverTripsIndexRoute: typeof DriverTripsIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverOnboardingRoute: DriverOnboardingRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverTransactionsRoute: DriverTransactionsRouteWithChildren,
  DriverVehiclesRoute: DriverVehiclesRoute,
  DriverWalletRoute: DriverWalletRoute,
  DriverIndexRoute: DriverIndexRoute,
  DriverTripsIdRoute: DriverTripsIdRouteWithChildren,
  DriverTripsNewRoute: DriverTripsNewRoute,
  DriverTripsIndexRoute: DriverTripsIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  ShareRoute: ShareRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  DriverRoute: DriverRouteWithChildren,
  TripsIdLocationRoute: TripsIdLocationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
